#.properties 에서 한글 사용을 하려면 꼭 인코딩을 UTF-8로 바꿔야 한다.
#.Spring boot 에 mybatis 가 포함되면 실행할 때 db 접속인 DataSource 를 컨테이너에서 생성하기 때문에 접속 정보를 꼭 작성해야 한다.
#.spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/webAppBoard
#.spring.datasource.username=boardServerDev
#.spring.datasource.password=mysql123

#.yml: \uBD80\uBAA8 \uC790\uC190 \uAD00\uACC4\uB85C \uD45C\uD604\uB41C\uB2E4.
spring:
  datasource:
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/WebAppBoard
    url: jdbc:log4jdbc:mysql://${MYSQL_HOST:localhost}:3306/WebAppBoard
    username: boardServerDev
    password: mysql123
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #DriverSpy :테스트시 중간에 개입하여 sql데이터를 훔쳐옴 -> 테스트 할때만 사용




mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.acorn.springboardstudy.dto
  #패키지명 미리 작성